name: Self-Hosted Runner Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run build
        run: mvn clean install
