name: Simple Java CI with Manual Approval

on:
  push:
    branches:
      - main
      - uat
      - dev
  pull_request:
    branches:
      - main
      - uat
      - dev

jobs:
  build:
    runs-on: self-hosted
    environment:
      name: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile and test the project
        run: mvn clean install

      - name: Package the project
        run: mvn package

      - name: Build Docker Image
        run: |
          docker build -t appjava:${{ github.sha }} .

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Tag Docker image for ACR
        run: |
          docker tag appjava:${{ github.sha }} anshulacr01.azurecr.io/appjava:${{ github.sha }}

      - name: Push Docker Image to ACR
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/appjava:${{ github.sha }}

      - name: Notify build success
        run: echo "Build and package completed, Docker image pushed to ACR!"

  deploy_to_dev:
    runs-on: self-hosted
    environment:
      name: dev
    needs: build
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to development
        run: echo "Deploying to development environment"

      - name: Notify deployment success
        run: echo "Deployment to development was successful!"

  deploy_to_uat:
    runs-on: self-hosted
    environment:
      name: uat
    needs: build
    if: github.ref == 'refs/heads/uat'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to UAT
        run: echo "Deploying to UAT environment"

      - name: Notify deployment success
        run: echo "Deployment to UAT was successful!"

  deploy_to_production:
    runs-on: self-hosted
    environment:
      name: production
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: echo "Deploying to production environment"
